version: 0.2
phases:
  install:
    commands:
      - echo "install step"
      - npm install
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build step"
      - gatsby build
  post_build:
    commands:
      - echo "post_build step"
      - aws s3 sync --delete public/ "s3://brunnertechnicalservices.com"
